
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\fuzhe\OneDrive\Desktop\cs hw\gui\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1455x1041")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1041,
    width = 1455,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    1070.0,
    0.0,
    1455.0,
    1041.0,
    fill="#79BCF7",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1163.0,
    y=47.5,
    width=201.0,
    height=83.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1163.0,
    y=217.0,
    width=201.0,
    height=83.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1163.0,
    y=398.0,
    width=201.0,
    height=83.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1163.0,
    y=587.0,
    width=201.0,
    height=83.0
)

canvas.create_text(
    178.0,
    20.0,
    anchor="nw",
    text="Conflict",
    fill="#094478",
    font=("Jomolhari Regular", 36 * -1)
)

canvas.create_rectangle(
    34.0,
    108.0,
    1034.0,
    228.0,
    fill="#DAEBF9",
    outline="")

canvas.create_text(
    78.0,
    149.0,
    anchor="nw",
    text="Conflict 1  ",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    275.0,
    149.0,
    anchor="nw",
    text="EH101",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    428.0,
    149.0,
    anchor="nw",
    text="Room conflict with EH 201",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=855.0,
    y=133.0,
    width=139.0,
    height=69.0
)

canvas.create_rectangle(
    34.0,
    287.0,
    1034.0,
    407.0,
    fill="#DAEBF9",
    outline="")

canvas.create_text(
    78.0,
    328.0,
    anchor="nw",
    text="Conflict 1  ",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    275.0,
    328.0,
    anchor="nw",
    text="EH101",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    428.0,
    328.0,
    anchor="nw",
    text="Room conflict with EH 201",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=855.0,
    y=312.0,
    width=139.0,
    height=69.0
)

canvas.create_rectangle(
    34.0,
    464.0,
    1034.0,
    584.0,
    fill="#DAEBF9",
    outline="")

canvas.create_text(
    78.0,
    505.0,
    anchor="nw",
    text="Conflict 1  ",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    275.0,
    505.0,
    anchor="nw",
    text="EH101",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    428.0,
    505.0,
    anchor="nw",
    text="Room conflict with EH 201",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=855.0,
    y=489.0,
    width=139.0,
    height=69.0
)

canvas.create_rectangle(
    36.0,
    657.0,
    1036.0,
    777.0,
    fill="#DAEBF9",
    outline="")

canvas.create_text(
    80.0,
    698.0,
    anchor="nw",
    text="Conflict 1  ",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    277.0,
    698.0,
    anchor="nw",
    text="EH101",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=857.0,
    y=682.0,
    width=139.0,
    height=69.0
)

canvas.create_text(
    430.0,
    698.0,
    anchor="nw",
    text="Room conflict with EH 201",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_rectangle(
    36.0,
    850.0,
    1036.0,
    970.0,
    fill="#DAEBF9",
    outline="")

canvas.create_text(
    80.0,
    891.0,
    anchor="nw",
    text="Conflict 1  ",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    277.0,
    891.0,
    anchor="nw",
    text="EH101",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

canvas.create_text(
    430.0,
    891.0,
    anchor="nw",
    text="Room conflict with EH 201",
    fill="#094478",
    font=("Jomolhari Regular", 24 * -1)
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=857.0,
    y=875.0,
    width=139.0,
    height=69.0
)
window.resizable(False, False)
window.mainloop()
