
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path
from PIL import Image, ImageTk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = Path(r"C:\Users\fuzhe\OneDrive\Desktop\cs hw\gui\assets\frame5")

class SettingsPage():

    def __init__(self, root):
        self.root = root
            
        self.fillWindow()


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    def fillWindow(self):

        canvas = Canvas(
            self.window,
            bg = "#FFFFFF",
            height = 1041,
            width = 1455,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            1.0,
            235.0,
            1042.0, 
            fill="#79BCF7",
            outline="")

    
        canvas.create_rectangle(
            296.0,
            41.0,
            1403.0,
            148.0,
            fill="#DAEBF9",
            outline="")

        canvas.create_text(
            323.0,
            76.0,
            anchor="nw",
            text="Font Setting:",
            fill="#094478",
            font=("Jomolhari Regular", 24 * -1)
        )

        button_image_6 = PhotoImage(
            file=self.relative_to_assets("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        button_6.place(
            x=503.0,
            y=64.0,
            width=169.0,
            height=66.0
        )

        button_image_7 = PhotoImage(
            file=self.relative_to_assets("button_7.png"))
        button_7 = Button(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_7 clicked"),
            relief="flat"
        )
        button_7.place(
            x=503.0,
            y=64.0,
            width=169.0,
            height=66.0
        )

        button_image_8 = PhotoImage(
            file=self.relative_to_assets("button_8.png"))
        button_8 = Button(
            image=button_image_8,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_8 clicked"),
            relief="flat"
        )
        button_8.place(
            x=959.0,
            y=64.0,
            width=169.0,
            height=66.0
        )

        button_image_9 = PhotoImage(
            file=self.relative_to_assets("button_9.png"))
        button_9 = Button(
            image=button_image_9,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_9 clicked"),
            relief="flat"
        )
        button_9.place(
            x=1181.0,
            y=64.0,
            width=169.0,
            height=66.0
        )

        button_image_10 = PhotoImage(
            file=self.relative_to_assets("button_10.png"))
        button_10 = Button(
            image=button_image_10,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_10 clicked"),
            relief="flat"
        )
        button_10.place(
            x=727.0,
            y=64.0,
            width=169.0,
            height=66.0
        )

        canvas.create_rectangle(
            289.0,
            502.0,
            1396.0,
            609.0,
            fill="#DAEBF9",
            outline="")

        canvas.create_rectangle(
            289.0,
            697.0,
            1403.0,
            804.0,
            fill="#DAEBF9",
            outline="")

        button_image_11 = PhotoImage(
            file=self.relative_to_assets("button_11.png"))
        button_11 = Button(
            image=button_image_11,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_11 clicked"),
            relief="flat"
        )
        button_11.place(
            x=342.0,
            y=525.0,
            width=226.0,
            height=66.0
        )

        button_image_12 = PhotoImage(
            file=self.relative_to_assets("button_12.png"))
        button_12 = Button(
            image=button_image_12,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_12 clicked"),
            relief="flat"
        )
        button_12.place(
            x=729.0,
            y=525.0,
            width=226.0,
            height=66.0
        )

        button_image_13 = PhotoImage(
            file=self.relative_to_assets("button_13.png"))
        button_13 = Button(
            image=button_image_13,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_13 clicked"),
            relief="flat"
        )
        button_13.place(
            x=1116.0,
            y=525.0,
            width=226.0,
            height=66.0
        )

        canvas.create_rectangle(
            296.0,
            239.0,
            1403.0,
            346.0,
            fill="#DAEBF9",
            outline="")

        canvas.create_text(
            323.0,
            274.0,
            anchor="nw",
            text="Font Size:",
            fill="#094478",
            font=("Jomolhari Regular", 24 * -1)
        )

        canvas.create_text(
            296.0,
            430.0,
            anchor="nw",
            text="Default display mode of class schedule: ",
            fill="#094478",
            font=("Jomolhari Regular", 36 * -1)
        )

        canvas.create_rectangle(
            502.0,
            293.00000002561853,
            1350.0000066752837,
            298.0,
            fill="#094478",
            outline="")

        canvas.create_text(
            330.0,
            735.0,
            anchor="nw",
            text="Font Setting:",
            fill="#094478",
            font=("Jomolhari Regular", 24 * -1)
        )

        button_image_14 = PhotoImage(
            file=self.relative_to_assets("button_14.png"))
        button_14 = Button(
            image=button_image_14,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_14 clicked"),
            relief="flat"
        )
        button_14.place(
            x=551.0,
            y=718.0,
            width=298.0,
            height=66.0
        )

        button_image_15 = PhotoImage(
            file=self.relative_to_assets("button_15.png"))
        button_15 = Button(
            image=button_image_15,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_15 clicked"),
            relief="flat"
        )
        button_15.place(
            x=979.0,
            y=718.0,
            width=298.0,
            height=66.0
        )

        button_image_16 = PhotoImage(
            file=self.relative_to_assets("button_16.png"))
        button_16 = Button(
            image=button_image_16,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_16 clicked"),
            relief="flat"
        )
        button_16.place(
            x=377.0,
            y=888.0,
            width=348.0,
            height=94.0
        )

        button_image_17 = PhotoImage(
            file=self.relative_to_assets("button_17.png"))
        button_17 = Button(
            image=button_image_17,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_17 clicked"),
            relief="flat"
        )
        button_17.place(
            x=979.0,
            y=888.0,
            width=348.0,
            height=94.0
        )
        window.resizable(False, False)
        window.mainloop()
