
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\fuzhe\OneDrive\Desktop\cs hw\gui\assets\frame0")

class ViewPage():
    def __init__(self, root):
        self.root = root

        self.fillWindow()

        
    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    def fillWindow(self):

        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 1041,
            width = 1455,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            1.0,
            235.0,
            1042.0,
            fill="#79BCF7",
            outline="")

        canvas.create_rectangle(
            1063.0,
            0.0,
            1455.0,
            81.0,
            fill="#DAEBF9",
            outline="")

        entry_image_1 = PhotoImage(
            file=self.relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            1301.0,
            40.5,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=1167.0,
            y=14.0,
            width=268.0,
            height=51.0
        )

        image_image_2 = PhotoImage(
            file=self.relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            1116.0,
            41.0,
            image=image_image_2
        )

        canvas.create_text(
            1067.0,
            113.0,
            anchor="nw",
            text="SORT BY:",
            fill="#094478",
            font=("Jomolhari Regular", 20 * -1)
        )

        button_image_6 = PhotoImage(
            file=self.relative_to_assets("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        button_6.place(
            x=1167.0,
            y=864.0,
            width=200.0,
            height=101.0
        )

        button_image_7 = PhotoImage(
            file=self.relative_to_assets("button_7.png"))
        button_7 = Button(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_7 clicked"),
            relief="flat"
        )
        button_7.place(
            x=1204.0,
            y=107.0,
            width=134.0,
            height=41.0
        )
        window.resizable(False, False)
        window.mainloop()
